name: CI

on:
  push: 
    paths-ignore:
      - ".VERSION"
  pull_request:
    paths-ignore:
      - ".VERSION"

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check go mod
      run: |
        go mod tidy
        git diff --exit-code go.mod

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test
      run: go test -v ./...
